### ISSUE TITLE
Generator.ResumeAfter memory leak

### ISSUE THREAD

**Issue by innostory** [cschladetsch/Flow#7]
```C#
public bool ResumeAfter(ITransient other)
{
	if (IsNullOrEmpty(other))
	{
		Resume();
		return true;
	}

	Suspend();

	other.Completed += tr => Resume();

	return true;
}
```
The above event subscription create a reference to "other". I have a long running coroutine which create and resumeAfter many other coroutines, and because "other" can't be garbage collected, my system run out of memory. It should be unsubscribed like this:
```C#
TransientHandler onCompleted = null;
onCompleted = tr =>
{
    other.Completed -= onCompleted;
    Resume();
};
other.Completed += onCompleted;
```
Same for suspend etc,

I don't have accessibility to github atm (my company policy), so I can't make a pull request for this soon :(

**Comment by cschladetsch** [comment]
Thank you for the report. I'll look into it.

**Comment by cschladetsch** [comment]
Fixed.
